services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sync:/var/syncthing
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/syncthing.conf:/etc/nginx/syncthing.conf
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - syncthing
    networks:
      - default
      - publish

networks:
  publish:
    external: true
    name: ${NETWORK_NAME}
